### ISSUE TITLE
Where can I find the template that has refered in this docummentation?

### ISSUE THREAD

**Issue by skashan-ali** [awsdocs/aws-cur-user-guide#4]
After reading this text, I believe there is existing template that I can use.

"To use Athena, you must set up an AWS Glue crawler, an AWS Glue database, and an AWS Lambda event. Billing and Cost Management provides an AWS CloudFormation template that does this setup for you. Be sure to align the Region when using the template. This process shows how to use the Athena AWS CloudFormation template. "

**Comment by skashan-ali** [comment]
Before moving on to the next procedure, you must wait for the first AWS CUR to be delivered to your Amazon S3 bucket. It might take up to 8 hours for AWS to deliver your first report.

**Comment by wparad** [comment]
Why did you close this?
