### ISSUE TITLE
Where is the Athena CloudFormation template?

### ISSUE THREAD

**Issue by wparad** [awsdocs/aws-cur-user-guide#6]
#4 in [./doc_source/use-athena-cf.md](./doc_source/use-athena-cf.md)

There is no template included on this page, nor does it state how to get one.

**Comment by AustinAMeyer** [comment]
I have this same concern.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
