### ISSUE TITLE
Link to 'P' in Lineitem-columns.md is incorrect

### ISSUE THREAD

**Issue by ckbux** [awsdocs/aws-cur-user-guide#7]
Hello!

The link to 'P' in Lineitem-columns.md links to: https://github.com/awsdocs/aws-cur-user-guide/blob/master/doc_source/billing-columns.md#b-P

It should link to: https://github.com/awsdocs/aws-cur-user-guide/blob/master/doc_source/Lineitem-columns.md#l-P

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
