### ISSUE TITLE
product/productSchemaDescription uses the word Carious

### ISSUE THREAD

**Issue by mikemilleresq** [awsdocs/aws-cur-user-guide#8]
Carious means decayed or expired, this does not make sense in this context and is a very odd word to use.  I believe it to be a typo for various.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
