### ISSUE TITLE
product/database_engine is missing from the Data Dictionary

### ISSUE THREAD

**Issue by doit-sclark** [awsdocs/aws-cur-user-guide#9]
### product/database_engine is missing from [Product Details](https://github.com/awsdocs/aws-cur-user-guide/blob/49d446bcddbd4135f73fdc9fa58d69d4aa614328/doc_source/product-columns.md).

The field is referenced in [Well Architected Labs Query Library](https://wellarchitectedlabs.com/cost/300_labs/300_cur_queries/queries/database/), and usually contains the DB Engine used for RDS DBs, such as `Aurora MySQL`, `MySQL`, etc. 

My company use the data dictionary to determine what we'll ingest, so it would be helpful to have it listed.  Can we get that added please?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
